# --- Laptop SSH Config (Michael) ---
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519

Host brain server
    HostName 100.70.100.118
    User michael
    IdentityFile ~/.ssh/id_ed25519

Host *
    AddKeysToAgent yes
    IdentitiesOnly yes
    IdentityFile ~/.ssh/id_ed25519
    ServerAliveInterval 60
